name: Set Repository Secrets Across Triune-Oracle Repos

on:
  workflow_dispatch:   # Manual trigger
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday at midnight UTC (adjust as needed)

jobs:
  update-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install tweetsodium node-fetch@2

      - name: Run set-secrets script
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: node set-secrets.js